name: flamegraph.com
on:
  pull_request:
  workflow_dispatch:

jobs:
  benchmark-cpu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Benchmark CPU
        run: go test -bench . -benchmem -benchtime 10s -cpuprofile cpu.out -o bench.exe ./...
      - name: Upload to flamegraph.com
        run: |
          go install github.com/google/pprof@latest
          pprof -proto bench.exe cpu.out
          cat profile001.pb.gz | curl --data-binary @- https://flamegraph.com
