name: flamegraph.com
on:
  pull_request:
  workflow_dispatch:

jobs:
  benchmark-cpu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ripgrep
          go install github.com/google/pprof@latest
      - name: Benchmark CPU
        run: |
          mkdir -p artifacts
          rg -INo --color 'never' -r '$1' -e '^func (Benchmark[a-zA-Z0-9_]+)' . | xargs -I% go test -bench ^%$ -benchtime 10s -cpuprofile artifacts/%.cpu.out -o artifacts/%.cpu.exe ./...
          ls -lah
          ls -lah artifacts
      - name: Upload to flamegraph.com
        run: |
          echo $(find artifacts/*.cpu.exe)
          echo $(find artifacts/*.cpu.exe | rg -INo --color 'never' -r '$1' -e '^artifacts/(.*)\.cpu\.exe$')
          find artifacts/*.cpu.exe | rg -INo --color 'never' -r '$1' -e '^artifacts/(.*)\.cpu\.exe$' | xargs -I% pprof -proto artifacts/%.cpu.exe artifacts/%.cpu.out
          ls -lah
          ls -lah artifacts
          find *.pb.gz | xargs -I% curl -sS --data-binary @% https://flamegraph.com | jq -r .url
