name: Benchmark (pyrobench)
on: [pull_request]
jobs:
  test:
    name: Bench
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.22
      uses: actions/setup-go@v5
      with:
        go-version: 1.22
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      with:
        fetch-depth: 1024

    # TODO: Pin release
    # TODO: Remove git-base
    # TODO: Provide output
    - name: Run Benchmark
      id: run_benchmarks
      run: |
        go run github.com/grafana/pyrobench@5208c1b -v compare --git-base dab464ec1f0bd3fe62d38be2aa8fec5dc34f0ba2 >> ids.txt

    - uses: actions/github-script@v7
      id: create-comment
      if: ${{ github.event_name == 'pull_request' }}
      with:
        github-token: ${{ secrets.PAT }}
        script: |
          return await github.rest.issues.listComments({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
          });

    - name: Get result
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        # echo '${{steps.create-comment.outputs.result}}'
        cat ids.txt
