on: issue_comment

jobs:
  pyrobench:
    name: Run Pyrobench on demand by PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Pyrobench
        uses: grafana/pyrobench@4ae055fe1e78e4d1b26e70253093c0fa13dad3a8
        with:
          github_context: ${{ toJson(github) }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
